site_name: Operating Systems
site_url: https://os.vlsm.ui.com/
repo_url: https://github.com/dimashn04/mkdocs-os-cbk
repo_name: mkdocs-os-cbk
nav:
  - Home: index.md
  - OS-Weekly:
      - assignments/index.md
  - Template:
      - template.md
theme:
  name: material
  logo: assets/images/cbk.jpg
  favicon: assets/images/cbk.jpg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: green
      accent: light green